import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./contexts/AuthContext";
import SiteHeader from "./components/features/SiteHeader";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Magic Monitor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthContextProvider>
          <SiteHeader />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
