import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./contexts/AuthContext";
import SiteHeader from "./components/features/SiteHeader";
import SiteFooter from "./components/features/SiteFooter";
import { FavouritesProvider } from "./contexts/FavouritesContext";
import { NotifyProvider } from "./contexts/NotifyContext";
import Notification from "./components/features/Notification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Magic Monitor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <FavouritesProvider>
            <NotifyProvider>
              <Notification />
              <SiteHeader />
              {children}
            </NotifyProvider>
          </FavouritesProvider>
        </AuthContextProvider>
        <SiteFooter />
      </body>
    </html>
  );
}
